on:
    push:
      branches: main
    schedule:
      - cron: "0 9,16 * * 1-5"

jobs:
   import-data:
     runs-on: ubuntu-latest
     steps:
       - name: Set up R
         uses: r-lib/actions/setup-r@v2
 
       - name: Install packages
         uses: r-lib/actions/setup-r-dependencies@v2
         with:
           packages: |
             any::dplyr
             any::jsonlite
             any::httr
 
       - name: Check out repository
         uses: actions/checkout@v4
 
       - name: Create full movies JSON
         run: Rscript -e 'source("fetch.R")'
 
       - name: Commit results
         run: |
           git config --local user.email "brianq1987@gmail.com"
           git config --local user.name "BrianQ1987"
           git add movies_full.json
           git commit -m 'Data updated' || echo "No changes to commit"
           git push origin || echo "No changes to commit"